### ISSUE TITLE
dangerous bug !!!

### ISSUE THREAD

**Issue by mc007** [ibm-js/generator-amd-build#7]
Hi,
I am trying since days now to get a delite-app build and so i took the examples from test. When setting baseUrl other than ./bower_components: 

amdloader: {
            inlineText: true,
            baseUrl: '../../lib/ibm-js/',

it seems to ignore the 'outdir' variable and compresses the source sdk directories instead. 
My fault, i did commit sometime later the entire sdk directory and ruined over 15 repositories. I am really pissed :-(

well, just to let you know. 

module.exports = function (grunt) {
    'use strict';
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-amd-build');
    grunt.loadNpmTasks("grunt-contrib-uglify");

    var outprop = 'amdoutput';
    var deploydir = './deploy/';
    var outdir = '../delite-app-xfile-build/';
    var tmpdir = './tmp/';
    var common = {
        options: { banner: '<%= ' + outprop + '.header%>' },
        src: '<%= ' + outprop + '.modules.abs %>',
        dest: outdir + '<%= ' + outprop + '.layerPath %>'
    };
    grunt.initConfig({
        amdloader: {
            inlineText: true,
            baseUrl: '../../lib/ibm-js/',
            packages: [
                {
                    name: 'myapp',
                    location: '../../apps/delite-app-xfile/myapp'
                },
                {
                    name: 'mypackage',
                    location: '../mylocalpackage'
                },
                {
                    name: 'jquery',
                    location: 'jquery',
                    main:'jquery'
                }
            ],
            map: {
                'mypackage/foo': {
                    'mypackage/bar': '../bar-mapped'
                },
                jquery: {
                    "jquery/src/selector": "jquery/src/selector-native"     // don't pull in sizzle
                }
            },
            paths: {
                'css': '../css',
                'mypackage/foo': '../patch/foo',
                'angular': 'angular/angular',
                'angular-loader': 'angular-loader/angular-loader'
                /*'jquery':'jquery/src/jquery'*/
                /*'jquery': '../../apps/delite-app-xfile/bower_components/jquery/dist/jquery'*/
            },
            shim: {
                'angular': {
                    exports: 'angular',
                    deps: ['angular-loader']
                },
                'angular-loader': {}
            },
            config: { 'requirejs-dplugins/i18n': { locale: 'fr-fr' } }
        },
        amdbuild: {
            buildPlugin: true,
            dir: tmpdir,
            runtimePlugins: [],
            layers: [{
                name: 'myapp/src'
            }]
        },
        amdreportjson: {
            dir: outdir
        },
        concat: {
            options: { separator: ';\n' },
            dist: common
        },
        copy: {
            plugins: {
                expand: true,
                cwd: tmpdir,
                src: '<%= ' + outprop + '.plugins.rel %>',
                dest: outdir
            },
            deploy: {
                expand: true,
                cwd: outdir + '<%= amdloader.baseUrl %>',
                src: '**/*',
                dest: deploydir,
                dot: true
            }
        },
        clean: {
            finish: [tmpdir]
        },
        // Config to allow uglify to generate the layer.
        uglify: {
            options: {
                banner: "<%= " + outprop + ".header%>",
                sourceMap: true
            },
            dist: {
                src: "<%= " + outprop + ".modules.abs %>",
                dest: outdir + "<%= " + outprop + ".layerPath %>"
            }
        },
        'closure-compiler': {
            frontend: {
                closurePath: '/PMaster/sdk/closure-compiler',
                js: outdir + 'myapp/src2.js',
                jsOutputFile: outdir + '/myapp/src.js',
                options: {
                    compilation_level: 'ADVANCED_OPTIMIZATIONS',
                    language_in: 'ECMASCRIPT5_STRICT'

                },
                maxBuffer: 5000000/*,
                options: {
                    compilation_level: 'ADVANCED_OPTIMIZATIONS',
                    language_in: 'ECMASCRIPT5_STRICT'
                }
                */
            }
        }

    });
    console.log('out dir' + outdir);
    console.log('tmp dir' + tmpdir);
    console.log('tmp dir' + deploydir);

    grunt.registerTask('amdbuild', function (amdloader) {
        var name = this.name, layers = grunt.config(name).layers;
        layers.forEach(function (layer) {
            grunt.task.run("amdshim:" + layer.name + ":" + name + ":" + amdloader);
            grunt.task.run('amddepsscan:' + layer.name + ':' + name + ':' + amdloader);
            grunt.task.run('amdserialize:' + layer.name + ':' + name + ':' + outprop);
            grunt.task.run('concat');
            //grunt.task.run('closure-compiler');
            //grunt.task.run("uglify");
            grunt.task.run('copy:plugins');
        });
    });
    grunt.registerTask('build', [
        'amdbuild:amdloader',
        'amdreportjson:amdbuild',
        'clean:finish'
    ]);
    grunt.registerTask('deploy', ['copy:deploy']);
};

**Comment by mc007** [comment]
i moved to require.js only, despite the missing plugin support during build. solved for me. thanks for the heads up.

**Comment by clmath** [comment]
Thanks for the report. This should be fixed by https://github.com/ibm-js/grunt-amd-build/commit/4a7aaf8dcb364fdcdbc19f3b19dd93c12c1e7f95. 

See also https://github.com/ibm-js/grunt-amd-build/issues/16
